### PR TITLE
gnome-shell 3.36.1 compatibility

### PR DESCRIPTION
**Pull request by jcarle**

### CODE REVIEW

**Comment by jcarle** [comment]
I have tried to fix the errors that occur in gnome-shell 3.36.1
Please check if it's ok.

Thank you

**Comment by RandieM** [comment]
It works on Fedora 32/Gnome 3.36.2.

**Comment by nicjohnston** [comment]
Unfortunately this stopped working with Gnome 3.36.4 on Debian testing.
The extension loads, and seems to allow window selection, but doesn't display anything.
Checking the logs shows the following error message being generated when selecting a window to preview.

```
gnome-shell[3009]: JS ERROR: TypeError: this._container.foreach is not a function
    _setThumbnail@/home/nic/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it/preview.js:410:25
    set window@/home/nic/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it/preview.js:633:14
    _onUserTriggered/</</<@/home/nic/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it/indicator.js:141:21
    activate@resource:///org/gnome/shell/ui/popupMenu.js:191:14
    vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14
```
